DROP TABLE IF EXISTS HierarchicalProcesses;
CREATE TABLE [HierarchicalProcesses] 
(
	[ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	[Depth] INTEGER NULL,
	[HasChildren] BOOLEAN NULL,
	[ProcessId] INTEGER NULL,
	FOREIGN KEY(ProcessId) REFERENCES Processes(ID) ON DELETE SET NULL
);

DROP TABLE IF EXISTS HookTrustStatus;
CREATE TABLE IF NOT EXISTS HookTrustStatus
(
	[ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	[TrustStatus] TEXT NULL,
	[HookId] INTEGER NULL,
	FOREIGN KEY(HookId) REFERENCES Hooks(ID) ON DELETE SET NULL
);

DROP TABLE IF EXISTS DeviceTree;
CREATE TABLE IF NOT EXISTS DeviceTree
(
	[ID] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	[Depth] INTEGER NULL,
	[HasChildren] BOOLEAN NULL,
	[DeviceType] TEXT NULL,
	[Name] TEXT NULL,
	[TrustStatus] TEXT NULL,
	[DriverId] INTEGER NULL,
	[DeviceId] INTEGER NULL,
	FOREIGN KEY( DriverId ) REFERENCES DriverItems(ID) ON DELETE SET NULL,
	FOREIGN KEY( DeviceId ) REFERENCES DeviceItems(ID) ON DELETE SET NULL 
);